version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
      - ./components:/components # Mount the components directory
    depends_on:
      - postgres_db
      - broker
    ports:
      - "8003:8000" # Updated port for the payment service
    networks:
      - default
    # command: ["dapr", "run", "--app-id", "payment-service", "--app-port", "8003", "--dapr-http-port", "3503", "--resources-path", "/components"]
    environment:
      DAPR_HTTP_PORT: 3503

volumes:
  postgres_db:
    external: true # Use external volume managed by the external compose.yaml

networks:
  default:
    external: true # Use external network managed by the external compose.yaml
