services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/code
    depends_on:
      - postgres_db
      - broker
    ports:
      - "8006:8000"
    networks:
      - default



volumes:
  postgres_db:
    external: true # Use external volume managed by the external compose.yaml

networks:
  default:
    external: true # Use external network managed by the external compose.yaml
