apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: broker:19092
    - name: consumerGroup
      value: payment-service-group
    - name: clientID
      value: payment-service-client
    - name: authType
      value: "none"
    - name: authentication.enabled
      value: "false"
    - name: authentication.username
      value: ""
    - name: authentication.password
      value: ""
    - name: tls.enabled
      value: "false"
    - name: tls.caCert
      value: ""
    - name: tls.cert
      value: ""
    - name: tls.key
      value: ""
