---
_format_version: "3.0"
services:
  - name: product-service
    url: http://product_service:8004
    routes:
      - name: product-route
        paths:
          - /products
        strip_path: false
  - name: payment-service
    url: http://payment_service:8003
    routes:
      - name: payment-route
        paths:
          - /payments
        strip_path: false
  - name: order-service
    url: http://order_service:8002
    routes:
      - name: order-route
        paths:
          - /orders
        strip_path: false
  - name: notification-service
    url: http://notification_service:8001
    routes:
      - name: notification-route
        paths:
          - /notifications
        strip_path: false
  - name: inventory-service
    url: http://inventory_service:8007
    routes:
      - name: inventory-route
        paths:
          - /inventory
        strip_path: false
  - name: user-service
    url: http://user_service:8005
    routes:
      - name: user-route
        paths:
          - /users
        strip_path: false
