apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka-pubsub
  namespace: default
spec:
  type: pubsub.kafka
  version: v1
  metadata:
    - name: brokers
      value: broker:19092
    - name: consumerGroup
      value: inventory-service-group
    - name: authType
      value: none
    - name: authentication.enabled
      value: "false"
    - name: authentication.username
      value: ""
    - name: authentication.password
      value: ""
    - name: tls.enabled
      value: "false"
